# Generated by Django 2.0.3 on 2018-04-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('IT', 'IT'), ('EE', 'EE'), ('AEIE', 'AEIE')], default='all', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default='all', max_length=4),
        ),
    ]
