# Generated by Django 2.0.3 on 2018-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180428_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dept',
            field=models.CharField(choices=[('ALL', 'ALL'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('IT', 'IT'), ('EE', 'EE'), ('AEIE', 'AEIE')], default='ALL', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('ALL', 'ALL'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default='ALL', max_length=4),
        ),
    ]
