# Generated by Django 2.0.1 on 2018-04-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180424_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('YEAR', 'Year'), ('DEPARTMENT', 'Department'), ('ALL', 'All')], default='all', max_length=20),
        ),
    ]
