# Generated by Django 2.0.3 on 2018-04-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180422_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stream',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('IT', 'IT'), ('EE', 'EE'), ('AEIE', 'AEIE')], default='CSE', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='Student', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roll',
            field=models.CharField(default='RollYear/NNN', max_length=11),
        ),
    ]
