# Generated by Django 2.0.1 on 2018-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180425_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('IT', 'IT'), ('EE', 'EE'), ('AEIE', 'AEIE')], default='CSE', max_length=5),
        ),
    ]
